# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "02:42" # UTC
    commit-message:
      prefix: "build(cargo):"
    groups:
      patches:
        update-types: ["patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:42" # UTC
    commit-message:
      prefix: "ci(actions):"
